config/routes.rb
Findafeast::Application.routes.draw do
  resources :feasts

  resources :users

  root 'restaurants#index'

  resources :restaurants do
    resources :feasts
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  SEARCHABLE_ATTRIBUTES = [:location, :cuisine, :price]

  LOCATIONS = ['Alexandra Road', 'Anson Road', 'Balmoral', 'Beach Road', 'Bencoolen', 'Boat Quay', 'Bugis', 'Bukit Timah', 'Buona Vista', 'City Hall', 'Dover', 'Eunos', 'Farrer Park', 'Geylang', 'Grange Road', 'Havelock Road', 'High Street', 'Holland Village', 'Kallang', 'Kembangan', 'Keppel Bay', 'Killiney', 'Little India', 'Macpherson', 'Marina Square', 'Marine Parade', 'Mount Faber', 'Neil Road', 'Newton', 'North Bridge Road', 'Orchard', 'Oxley', 'Pasir Panjang', 'Paya Lebar', 'Potong Pasir', 'Queenstown', 'Raffles Place', 'River Valley', 'Rochor', 'Sentosa', 'Serangoon Road', 'Shenton Way', 'Suntec City', 'Tanglin Road', 'Tanjong Pagar', 'Tanjong Rhu', 'Telok Blangah', 'Tiong Bahru', 'West Coast'].sort
  CUISINES = ['Japanese', 'Chinese', 'Singaporean', 'Vietnamese', 'French', 'Italian', 'American', 'Taiwanese', 'Korean', 'Thai', 'Spanish'].sort
  PRICES = [
    ['$', 1],
    ['$$', 2],
    ['$$$', 3],
    ['$$$$', 4],
    ['$$$$$', 5],
  ]

  has_many :feasts

  def display_price
    price.times.map { '$' }.join
  end

  def to_s
    name
  end

  COVER_URL = [
    'https://lh3.ggpht.com/-2WMltLZiXHU/UH6g3jrmuzI/AAAAAAAAEVs/kAEYRsYrK6Q/s1600/Equinox+SG.jpg',
    'http://retaildesignblog.net/wp-content/uploads/2013/09/Kaiseki-Yoshiyuki-restaurant-by-B3-Designers-Singapore.jpg',
    'http://static.asiawebdirect.com/m/phuket/portals/www-singapore-com/homepage/food-dining/TopPageContent/0/BigImage/singapore-dining-740.jpg',
    'http://www.district10.com.sg/img/uesquare/201311DSC_5941.jpg',
    'http://www.district10.com.sg/img/uesquare/201311PrivateDiningRoom.jpg',
    'http://www.district10.com.sg/img/uesquare/201311OutdoorArea2.jpg',
    'http://www.district10.com.sg/img/uesquare/201311TheBarArea.jpg',
    'http://www.district10.com.sg/img/uesquare/201311TheDiningRoom.jpg',
    'http://www.district10.com.sg/img/starvista/tsv3.jpg',
    'http://www.district10.com.sg/img/starvista/tsv7.jpg',
    'https://scontent-a-pao.xx.fbcdn.net/hphotos-ash3/t31/1269020_10201014479837695_340929700_o.jpg',
    'https://fbcdn-sphotos-b-a.akamaihd.net/hphotos-ak-ash3/t31/922110_4490308909322_1443370088_o.jpg',
    'https://scontent-a-pao.xx.fbcdn.net/hphotos-prn1/t1/p180x540/564614_10200576994860844_610310968_n.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-frc3/t1/q71/s720x720/1450210_10200497576835443_1391164948_n.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-ash3/t1/p180x540/1385127_10200328417206558_1055145704_n.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-frc3/t1/p180x540/1003649_4643039127482_350356317_n.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-frc3/t31/s720x720/891688_4379605861815_2055460588_o.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-frc1/t31/s720x720/902105_4379604381778_1545155531_o.jpg',
    'https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-frc1/t31/s720x720/892034_4379602981743_1263099535_o.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-frc1/t31/s720x720/904059_4379602061720_992702927_o.jpg',
    'https://fbcdn-sphotos-a-a.akamaihd.net/hphotos-ak-frc3/t31/s720x720/893773_4379595581558_657176655_o.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-prn1/t31/p480x480/778795_3979001446955_704899980_o.jpg',
    'https://scontent-a-pao.xx.fbcdn.net/hphotos-prn1/t31/p180x540/735491_3831245593151_2081951274_o.jpg',
    'https://scontent-b-pao.xx.fbcdn.net/hphotos-prn1/t31/s720x720/56302_3546600837210_1107105520_o.jpg'
  ].shuffle

  def cover_url
    if id.present?
      COVER_URL[id % COVER_URL.length]
    end
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    Restaurant::SEARCHABLE_ATTRIBUTES.each do |attribute|
      @restaurants = @restaurants.where(attribute => params[attribute]) if params[attribute].present?
    end
    @restaurants = @restaurants.decorate
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = @restaurant.decorate
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render action: 'show', status: :created, location: @restaurant }
      else
        format.html { render action: 'new' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :phone, *Restaurant::SEARCHABLE_ATTRIBUTES)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.select :price, options_for_select(Restaurant::PRICES, @restaurant.price), {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :cuisine %>
    <%= f.select :cuisine, options_for_select(Restaurant::CUISINES, @restaurant.cuisine), {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.select :location, options_for_select(Restaurant::LOCATIONS, @restaurant.location), {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.button 'Create Restaurant', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1></h1>

<div class="row">
  <div class="col-md-3">
    <h4>
      Search for restaurants
    </h4>
    <%= form_tag(restaurants_path, method: "get") do %>
      <div class="form-group">
        <%= label_tag :party, 'Party of?' %>
        <%= select_tag :party,
          options_for_select(
            (2..10).to_a,
            params[:party]
          ),
          class: 'form-control'
        %>
      </div>

      <div class="form-group">
        <%= label_tag :location, 'Location' %>
        <%= select_tag :location,
          options_for_select(
            [''] + Restaurant::LOCATIONS,
            params[:location]
          ),
          class: 'form-control'
        %>
      </div>

      <div class="form-group">
        <%= label_tag :cuisine, 'Cuisine' %>
        <%= select_tag :cuisine,
          options_for_select(
            [''] + Restaurant::CUISINES,
            params[:cuisine]
          ),
          class: 'form-control'
        %>
      </div>

      <div class="form-group">
        <%= label_tag :price, 'Price' %>
        <%= select_tag :price,
          options_for_select(
            [''] + Restaurant::PRICES,
            params[:price]
          ),
          class: 'form-control'
        %>
      </div>

      <!-- <div class="form-group">
        <%= label_tag :q, "Name" %>
        <%= text_field_tag :q, params[:q], class: 'form-control' %>
      </div> -->

      <%= button_tag 'Search', class: 'btn btn-default' %>
    <% end %>
  </div>
  <div class="col-md-9">
    <h4>
      Restaurants
    </h4>
    <% @restaurants.each do |restaurant| %>
      <div class="media">
        <%= link_to restaurant, class: 'pull-left' do %>
          <div class="restaurant-thumb" style="background-image: url('<%= restaurant.cover_url%>')">
          </div>
        <% end %>
        <div class="media-body">
          <h3 class="media-heading">
            <%= link_to restaurant, restaurant %>
          </h3>
          <div>
            <%= restaurant.info_span %>
          </div>
          <p>
            <%= restaurant.description %>
          </p>
          <div>
            <%= link_to 'Explore Menu', restaurant, class: 'btn btn-default' %>
            <%= link_to 'Start a Feast', new_restaurant_feast_path(restaurant), class: 'btn btn-default' %>
          </div>
        </div>
      </div>
    <% end %>
    <% if @restaurants.empty? %>
      No restaurants found
    <% end %>
  </div>
</div>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<% content_for :outside_container do %>
  <div class="jumbotron restaurant-jumbotron" style="background-image: url('<%= @restaurant.cover_url%>'); background-size: 100% auto; background-opacity: 0.1;">
    <div class="container">
      <h1><%= @restaurant.name %></h1>
      <p><%= @restaurant.info_span %></p>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-9">
    <p>
      <%= @restaurant.description %>
    </p>
    <p>
      <%= link_to 'Start a Feast', new_restaurant_feast_path(@restaurant), class: 'btn btn-default' %>
    </p>
  </div>
  <div class="col-md-3">
    <h4>Where to find?</h4>
    <p>
      <%= @restaurant.address %>
    </p>
    <p>
      <%= @restaurant.phone %>
    </p>
  </div>
</div>
<!-- <%= link_to 'Back', restaurants_path %> -->