config/routes.rb
Findafeast::Application.routes.draw do
  resources :feasts

  resources :users

  root 'restaurants#index'

  resources :restaurants do
    resources :feasts
  end

end

app/models/feast.rb
class Feast < ActiveRecord::Base
  belongs_to :restaurant
  has_and_belongs_to_many :users
  # attr_accessible :user_tokens
  attr_reader :user_tokens

  def default_name
    "Dinner at #{restaurant}!"
  end

  def user_tokens=(tokens)
    self.user_ids = User.ids_from_tokens(tokens)
  end
end

app/controllers/feasts_controller.rb
class FeastsController < ApplicationController
  before_action :set_feast, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant, only: [:new]


  # GET /feasts
  # GET /feasts.json
  def index
    @feasts = Feast.all
  end

  # GET /feasts/1
  # GET /feasts/1.json
  def show
    @restaurant = @feast.restaurant.decorate
  end

  # GET /feasts/new
  def new
    @feast = Feast.new(restaurant_id: @restaurant.id)
    @feast.name = @feast.default_name
  end

  # GET /feasts/1/edit
  def edit
  end

  # POST /feasts
  # POST /feasts.json
  def create
    @feast = Feast.new(feast_params)

    respond_to do |format|
      if @feast.save
        format.html { redirect_to @feast, notice: 'Feast was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feast }
      else
        format.html { render action: 'new' }
        format.json { render json: @feast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feasts/1
  # PATCH/PUT /feasts/1.json
  def update
    respond_to do |format|
      if @feast.update(feast_params)
        format.html { redirect_to @feast, notice: 'Feast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feasts/1
  # DELETE /feasts/1.json
  def destroy
    @feast.destroy
    respond_to do |format|
      format.html { redirect_to feasts_url }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id]).decorate
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_feast
      @feast = Feast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feast_params
      params.require(:feast).permit(:name, :description, :restaurant_id, :user_tokens, :time)
    end
end

app/helpers/feasts_helper.rb
module FeastsHelper
end

app/views/feasts/_form.html.erb
<%= form_for(@feast) do |f| %>
  <% if @feast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feast.errors.count, "error") %> prohibited this feast from being saved:</h2>

      <ul>
      <% @feast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :users %>
    <%= f.text_field :user_tokens, data: { load: @feast.users }, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :time %>
    <%= f.text_field :time, class: 'form-control' %>
  </div>

  <%= f.hidden_field :restaurant_id %>
  <div class="actions">
    <%= f.button 'Start Feast', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/feasts/edit.html.erb
<h1>Editing feast</h1>

<%= render 'form' %>

<%= link_to 'Show', @feast %> |
<%= link_to 'Back', feasts_path %>

app/views/feasts/index.html.erb
<h1>Listing feasts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Restaurant</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @feasts.each do |feast| %>
      <tr>
        <td><%= feast.name %></td>
        <td><%= feast.description %></td>
        <td><%= feast.restaurant %></td>
        <td><%= link_to 'Show', feast %></td>
        <td><%= link_to 'Edit', edit_feast_path(feast) %></td>
        <td><%= link_to 'Destroy', feast, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feast', new_feast_path %>

app/views/feasts/new.html.erb
<% content_for :outside_container do %>
  <div class="jumbotron restaurant-jumbotron" style="background-image: url('<%= @restaurant.cover_url%>'); background-size: 100% auto; background-opacity: 0.1;">
    <div class="container">
      <h1><%= @restaurant.name %></h1>
      <p><%= @restaurant.info_span %></p>
    </div>
  </div>
<% end %>

<h1>Start a feast at <%= @restaurant %></h1>

<%= render 'form' %>

app/views/feasts/show.html.erb
<% content_for :outside_container do %>
  <div class="jumbotron restaurant-jumbotron" style="background-image: url('<%= @restaurant.cover_url%>'); background-size: 100% auto; background-opacity: 0.1;">
    <div class="container">
      <h1><%= @feast.name %></h1>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-9">
    <p>
      <%= @feast.description %>
    </p>
    <p>
      <%= link_to 'Update details', edit_feast_path(@feast), class: 'btn btn-default' %>
      <%= link_to 'Add more people', edit_feast_path(@feast), class: 'btn btn-default' %>
    </p>
  </div>
  <div class="col-md-3">
    <h4>Who is going</h4>
    <p>
      <% @feast.users.each do |user| %>
        <%= user %>
      <% end %>
    </p>
    <h4>When</h4>
    <p>
      <%= @feast.time %>
    </p>
    <h4>Where to find?</h4>
    <p>
      <%= @restaurant.address %>
    </p>
    <p>
      <%= @restaurant.phone %>
    </p>
  </div>
</div>